spring:
  application:
    name: hd api
  datasource:
    url: "jdbc:postgresql://localhost:5432/hd"
    username: "hd"
    password: "hd"
#    driver-class-name: org.postgresql.Driver

management:
  health:
    ssl:
      enabled: false

app:
  api-username: dummy
  api-password: youShouldReallyChangeThis